[package]
name = "lust"
version = "0.1.0"
authors = ["Harrison Burt <57491488+ChillFish8@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
webp = "0.1"
image = "0.23"

base64 = "0.13.0"
bytes = "1"

anyhow = "1"
clap = "2"
serde_json = "1"
serde_variant = "0.1.0"
async-trait = "0.1.50"
once_cell = "1.7.2"
lru = "0.6.5"
parking_lot = "0.11.1"

log = "0.4.14"
simple_logger = "1.11.0"

gotham = "0.6.0"
gotham_derive = "0.6.0"
headers = "0.3"

tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
uuid = { version = "0.8.2", features = ["serde", "v4"] }
hashbrown = { version = "0.11.2", features = ["serde"] }
scylla = { git = "https://github.com/scylladb/scylla-rust-driver.git", branch = "main" }
sqlx = { version = "0.5", features = [ "runtime-tokio-rustls", "mysql", "sqlite", "postgres" ] }