backend:
  scylla:
    nodes:
      - "127.0.0.1:9042"
    keyspace: lust  # The keyspace must be created ahead of time.

base_serving_path: "/images"  # Serve buckets out of `/images`
global_cache:
  max_capacity: 500   # We set 500MB max cache capacity.

buckets:
  user-profiles:  # Define a bucket called "user-profiles", this is accessable out of `/images/user-profiles`.
    # mode: aot     # Optimise images as and when they're required then store them.
    # formats:
    #   png: true  # Enable PNG encoding.
    #   jpeg: true  # Enable JPEG encoding.
    #   webp: false  # Disable WebP encoding.
    #   gif: false  # Disable GIF encoding.
    #
    # default_serving_format: jpeg            # Serve the WebP format by default.
    #
    # cache: null  # Use the global cache handler.

    mode: aot     # Optimise images as and when they're required then store them.
    formats:
      png: true  # Disable PNG encoding.
      jpeg: true  # Enable JPEG encoding.
      webp: true  # Enable WebP encoding.
      gif: false  # Disable GIF encoding.

      original_image_store_format: jpeg

      webp_config:
        quality: 80       # Set lossy quality to 80%
        method: 4         # Opt on the side of performance slightly more than quality.
        threading: true   # Enable multi-threaded encoding.

    default_serving_format: png            # Serve the WebP format by default.
    default_serving_preset: medium-square   # Use the "medium-square" sizing preset by default.

    presets:
      medium-square:  # Define a new resizing preset.
        width: 500    # 500px
        height: 500   # 500px

    cache: null  # Use the global cache handler.

